import { Component, OnInit } from '@angular/core';
import { RestService } from '../../service/rest.service';
import { AppService } from '../../service/app.service'; 

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  searchText: string;
  searchResult: any = [];
  demoData: any = {
    'total_count': 5443,
    'incomplete_results': false,
    'items': [
      {
        'login': 'rameshkec85',
        'id': 1030165,
        'node_id': 'MDQ6VXNlcjEwMzAxNjU=',
        'avatar_url': 'https://avatars3.githubusercontent.com/u/1030165?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rameshkec85',
        'html_url': 'https://github.com/rameshkec85',
        'followers_url': 'https://api.github.com/users/rameshkec85/followers',
        'following_url': 'https://api.github.com/users/rameshkec85/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rameshkec85/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rameshkec85/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rameshkec85/subscriptions',
        'organizations_url': 'https://api.github.com/users/rameshkec85/orgs',
        'repos_url': 'https://api.github.com/users/rameshkec85/repos',
        'events_url': 'https://api.github.com/users/rameshkec85/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rameshkec85/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 84.04273
      },
      {
        'login': 'rameshvoltella',
        'id': 5446157,
        'node_id': 'MDQ6VXNlcjU0NDYxNTc=',
        'avatar_url': 'https://avatars3.githubusercontent.com/u/5446157?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rameshvoltella',
        'html_url': 'https://github.com/rameshvoltella',
        'followers_url': 'https://api.github.com/users/rameshvoltella/followers',
        'following_url': 'https://api.github.com/users/rameshvoltella/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rameshvoltella/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rameshvoltella/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rameshvoltella/subscriptions',
        'organizations_url': 'https://api.github.com/users/rameshvoltella/orgs',
        'repos_url': 'https://api.github.com/users/rameshvoltella/repos',
        'events_url': 'https://api.github.com/users/rameshvoltella/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rameshvoltella/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 78.265076
      },
      {
        'login': 'rameshvarun',
        'id': 889879,
        'node_id': 'MDQ6VXNlcjg4OTg3OQ==',
        'avatar_url': 'https://avatars2.githubusercontent.com/u/889879?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rameshvarun',
        'html_url': 'https://github.com/rameshvarun',
        'followers_url': 'https://api.github.com/users/rameshvarun/followers',
        'following_url': 'https://api.github.com/users/rameshvarun/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rameshvarun/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rameshvarun/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rameshvarun/subscriptions',
        'organizations_url': 'https://api.github.com/users/rameshvarun/orgs',
        'repos_url': 'https://api.github.com/users/rameshvarun/repos',
        'events_url': 'https://api.github.com/users/rameshvarun/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rameshvarun/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 75.065956
      },
      {
        'login': 'hiddentao',
        'id': 266594,
        'node_id': 'MDQ6VXNlcjI2NjU5NA==',
        'avatar_url': 'https://avatars0.githubusercontent.com/u/266594?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/hiddentao',
        'html_url': 'https://github.com/hiddentao',
        'followers_url': 'https://api.github.com/users/hiddentao/followers',
        'following_url': 'https://api.github.com/users/hiddentao/following{/other_user}',
        'gists_url': 'https://api.github.com/users/hiddentao/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/hiddentao/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/hiddentao/subscriptions',
        'organizations_url': 'https://api.github.com/users/hiddentao/orgs',
        'repos_url': 'https://api.github.com/users/hiddentao/repos',
        'events_url': 'https://api.github.com/users/hiddentao/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/hiddentao/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 70.371506
      },
      {
        'login': 'rameshksh',
        'id': 9266341,
        'node_id': 'MDQ6VXNlcjkyNjYzNDE=',
        'avatar_url': 'https://avatars1.githubusercontent.com/u/9266341?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rameshksh',
        'html_url': 'https://github.com/rameshksh',
        'followers_url': 'https://api.github.com/users/rameshksh/followers',
        'following_url': 'https://api.github.com/users/rameshksh/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rameshksh/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rameshksh/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rameshksh/subscriptions',
        'organizations_url': 'https://api.github.com/users/rameshksh/orgs',
        'repos_url': 'https://api.github.com/users/rameshksh/repos',
        'events_url': 'https://api.github.com/users/rameshksh/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rameshksh/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 68.45317
      },
      {
        'login': 'sampathweb',
        'id': 1437573,
        'node_id': 'MDQ6VXNlcjE0Mzc1NzM=',
        'avatar_url': 'https://avatars2.githubusercontent.com/u/1437573?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/sampathweb',
        'html_url': 'https://github.com/sampathweb',
        'followers_url': 'https://api.github.com/users/sampathweb/followers',
        'following_url': 'https://api.github.com/users/sampathweb/following{/other_user}',
        'gists_url': 'https://api.github.com/users/sampathweb/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/sampathweb/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/sampathweb/subscriptions',
        'organizations_url': 'https://api.github.com/users/sampathweb/orgs',
        'repos_url': 'https://api.github.com/users/sampathweb/repos',
        'events_url': 'https://api.github.com/users/sampathweb/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/sampathweb/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 67.76598
      },
      {
        'login': 'ashwinr64',
        'id': 6336013,
        'node_id': 'MDQ6VXNlcjYzMzYwMTM=',
        'avatar_url': 'https://avatars0.githubusercontent.com/u/6336013?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/ashwinr64',
        'html_url': 'https://github.com/ashwinr64',
        'followers_url': 'https://api.github.com/users/ashwinr64/followers',
        'following_url': 'https://api.github.com/users/ashwinr64/following{/other_user}',
        'gists_url': 'https://api.github.com/users/ashwinr64/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/ashwinr64/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/ashwinr64/subscriptions',
        'organizations_url': 'https://api.github.com/users/ashwinr64/orgs',
        'repos_url': 'https://api.github.com/users/ashwinr64/repos',
        'events_url': 'https://api.github.com/users/ashwinr64/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/ashwinr64/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 64.59622
      },
      {
        'login': 'Rameshkumarpolavarapu',
        'id': 29473947,
        'node_id': 'MDQ6VXNlcjI5NDczOTQ3',
        'avatar_url': 'https://avatars3.githubusercontent.com/u/29473947?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/Rameshkumarpolavarapu',
        'html_url': 'https://github.com/Rameshkumarpolavarapu',
        'followers_url': 'https://api.github.com/users/Rameshkumarpolavarapu/followers',
        'following_url': 'https://api.github.com/users/Rameshkumarpolavarapu/following{/other_user}',
        'gists_url': 'https://api.github.com/users/Rameshkumarpolavarapu/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/Rameshkumarpolavarapu/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/Rameshkumarpolavarapu/subscriptions',
        'organizations_url': 'https://api.github.com/users/Rameshkumarpolavarapu/orgs',
        'repos_url': 'https://api.github.com/users/Rameshkumarpolavarapu/repos',
        'events_url': 'https://api.github.com/users/Rameshkumarpolavarapu/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/Rameshkumarpolavarapu/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 63.72117
      },
      {
        'login': 'rameshsyn',
        'id': 10565954,
        'node_id': 'MDQ6VXNlcjEwNTY1OTU0',
        'avatar_url': 'https://avatars1.githubusercontent.com/u/10565954?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rameshsyn',
        'html_url': 'https://github.com/rameshsyn',
        'followers_url': 'https://api.github.com/users/rameshsyn/followers',
        'following_url': 'https://api.github.com/users/rameshsyn/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rameshsyn/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rameshsyn/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rameshsyn/subscriptions',
        'organizations_url': 'https://api.github.com/users/rameshsyn/orgs',
        'repos_url': 'https://api.github.com/users/rameshsyn/repos',
        'events_url': 'https://api.github.com/users/rameshsyn/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rameshsyn/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 62.311375
      },
      {
        'login': 'Ramesh7128',
        'id': 7310684,
        'node_id': 'MDQ6VXNlcjczMTA2ODQ=',
        'avatar_url': 'https://avatars3.githubusercontent.com/u/7310684?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/Ramesh7128',
        'html_url': 'https://github.com/Ramesh7128',
        'followers_url': 'https://api.github.com/users/Ramesh7128/followers',
        'following_url': 'https://api.github.com/users/Ramesh7128/following{/other_user}',
        'gists_url': 'https://api.github.com/users/Ramesh7128/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/Ramesh7128/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/Ramesh7128/subscriptions',
        'organizations_url': 'https://api.github.com/users/Ramesh7128/orgs',
        'repos_url': 'https://api.github.com/users/Ramesh7128/repos',
        'events_url': 'https://api.github.com/users/Ramesh7128/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/Ramesh7128/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 61.93009
      },
      {
        'login': 'rameshvs',
        'id': 1247911,
        'node_id': 'MDQ6VXNlcjEyNDc5MTE=',
        'avatar_url': 'https://avatars1.githubusercontent.com/u/1247911?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rameshvs',
        'html_url': 'https://github.com/rameshvs',
        'followers_url': 'https://api.github.com/users/rameshvs/followers',
        'following_url': 'https://api.github.com/users/rameshvs/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rameshvs/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rameshvs/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rameshvs/subscriptions',
        'organizations_url': 'https://api.github.com/users/rameshvs/orgs',
        'repos_url': 'https://api.github.com/users/rameshvs/repos',
        'events_url': 'https://api.github.com/users/rameshvs/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rameshvs/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 61.54764
      },
      {
        'login': 'rameshthoomu',
        'id': 17034502,
        'node_id': 'MDQ6VXNlcjE3MDM0NTAy',
        'avatar_url': 'https://avatars0.githubusercontent.com/u/17034502?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rameshthoomu',
        'html_url': 'https://github.com/rameshthoomu',
        'followers_url': 'https://api.github.com/users/rameshthoomu/followers',
        'following_url': 'https://api.github.com/users/rameshthoomu/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rameshthoomu/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rameshthoomu/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rameshthoomu/subscriptions',
        'organizations_url': 'https://api.github.com/users/rameshthoomu/orgs',
        'repos_url': 'https://api.github.com/users/rameshthoomu/repos',
        'events_url': 'https://api.github.com/users/rameshthoomu/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rameshthoomu/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 60.554253
      },
      {
        'login': 'techscientist',
        'id': 7275205,
        'node_id': 'MDQ6VXNlcjcyNzUyMDU=',
        'avatar_url': 'https://avatars1.githubusercontent.com/u/7275205?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/techscientist',
        'html_url': 'https://github.com/techscientist',
        'followers_url': 'https://api.github.com/users/techscientist/followers',
        'following_url': 'https://api.github.com/users/techscientist/following{/other_user}',
        'gists_url': 'https://api.github.com/users/techscientist/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/techscientist/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/techscientist/subscriptions',
        'organizations_url': 'https://api.github.com/users/techscientist/orgs',
        'repos_url': 'https://api.github.com/users/techscientist/repos',
        'events_url': 'https://api.github.com/users/techscientist/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/techscientist/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 60.481186
      },
      {
        'login': 'RameshBhupathi',
        'id': 9985707,
        'node_id': 'MDQ6VXNlcjk5ODU3MDc=',
        'avatar_url': 'https://avatars2.githubusercontent.com/u/9985707?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/RameshBhupathi',
        'html_url': 'https://github.com/RameshBhupathi',
        'followers_url': 'https://api.github.com/users/RameshBhupathi/followers',
        'following_url': 'https://api.github.com/users/RameshBhupathi/following{/other_user}',
        'gists_url': 'https://api.github.com/users/RameshBhupathi/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/RameshBhupathi/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/RameshBhupathi/subscriptions',
        'organizations_url': 'https://api.github.com/users/RameshBhupathi/orgs',
        'repos_url': 'https://api.github.com/users/RameshBhupathi/repos',
        'events_url': 'https://api.github.com/users/RameshBhupathi/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/RameshBhupathi/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 58.816204
      },
      {
        'login': 'rkjha',
        'id': 759531,
        'node_id': 'MDQ6VXNlcjc1OTUzMQ==',
        'avatar_url': 'https://avatars3.githubusercontent.com/u/759531?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rkjha',
        'html_url': 'https://github.com/rkjha',
        'followers_url': 'https://api.github.com/users/rkjha/followers',
        'following_url': 'https://api.github.com/users/rkjha/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rkjha/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rkjha/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rkjha/subscriptions',
        'organizations_url': 'https://api.github.com/users/rkjha/orgs',
        'repos_url': 'https://api.github.com/users/rkjha/repos',
        'events_url': 'https://api.github.com/users/rkjha/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rkjha/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 57.82795
      },
      {
        'login': 'Rameshv',
        'id': 750555,
        'node_id': 'MDQ6VXNlcjc1MDU1NQ==',
        'avatar_url': 'https://avatars1.githubusercontent.com/u/750555?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/Rameshv',
        'html_url': 'https://github.com/Rameshv',
        'followers_url': 'https://api.github.com/users/Rameshv/followers',
        'following_url': 'https://api.github.com/users/Rameshv/following{/other_user}',
        'gists_url': 'https://api.github.com/users/Rameshv/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/Rameshv/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/Rameshv/subscriptions',
        'organizations_url': 'https://api.github.com/users/Rameshv/orgs',
        'repos_url': 'https://api.github.com/users/Rameshv/repos',
        'events_url': 'https://api.github.com/users/Rameshv/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/Rameshv/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 57.53746
      },
      {
        'login': 'RameshAditya',
        'id': 17107833,
        'node_id': 'MDQ6VXNlcjE3MTA3ODMz',
        'avatar_url': 'https://avatars2.githubusercontent.com/u/17107833?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/RameshAditya',
        'html_url': 'https://github.com/RameshAditya',
        'followers_url': 'https://api.github.com/users/RameshAditya/followers',
        'following_url': 'https://api.github.com/users/RameshAditya/following{/other_user}',
        'gists_url': 'https://api.github.com/users/RameshAditya/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/RameshAditya/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/RameshAditya/subscriptions',
        'organizations_url': 'https://api.github.com/users/RameshAditya/orgs',
        'repos_url': 'https://api.github.com/users/RameshAditya/repos',
        'events_url': 'https://api.github.com/users/RameshAditya/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/RameshAditya/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 56.99159
      },
      {
        'login': 'rameshrr',
        'id': 3594277,
        'node_id': 'MDQ6VXNlcjM1OTQyNzc=',
        'avatar_url': 'https://avatars2.githubusercontent.com/u/3594277?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rameshrr',
        'html_url': 'https://github.com/rameshrr',
        'followers_url': 'https://api.github.com/users/rameshrr/followers',
        'following_url': 'https://api.github.com/users/rameshrr/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rameshrr/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rameshrr/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rameshrr/subscriptions',
        'organizations_url': 'https://api.github.com/users/rameshrr/orgs',
        'repos_url': 'https://api.github.com/users/rameshrr/repos',
        'events_url': 'https://api.github.com/users/rameshrr/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rameshrr/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 56.407276
      },
      {
        'login': 'RameshbabuJaga',
        'id': 11292624,
        'node_id': 'MDQ6VXNlcjExMjkyNjI0',
        'avatar_url': 'https://avatars1.githubusercontent.com/u/11292624?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/RameshbabuJaga',
        'html_url': 'https://github.com/RameshbabuJaga',
        'followers_url': 'https://api.github.com/users/RameshbabuJaga/followers',
        'following_url': 'https://api.github.com/users/RameshbabuJaga/following{/other_user}',
        'gists_url': 'https://api.github.com/users/RameshbabuJaga/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/RameshbabuJaga/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/RameshbabuJaga/subscriptions',
        'organizations_url': 'https://api.github.com/users/RameshbabuJaga/orgs',
        'repos_url': 'https://api.github.com/users/RameshbabuJaga/repos',
        'events_url': 'https://api.github.com/users/RameshbabuJaga/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/RameshbabuJaga/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 53.410084
      },
      {
        'login': 'Rameshb-umd',
        'id': 13987424,
        'node_id': 'MDQ6VXNlcjEzOTg3NDI0',
        'avatar_url': 'https://avatars1.githubusercontent.com/u/13987424?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/Rameshb-umd',
        'html_url': 'https://github.com/Rameshb-umd',
        'followers_url': 'https://api.github.com/users/Rameshb-umd/followers',
        'following_url': 'https://api.github.com/users/Rameshb-umd/following{/other_user}',
        'gists_url': 'https://api.github.com/users/Rameshb-umd/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/Rameshb-umd/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/Rameshb-umd/subscriptions',
        'organizations_url': 'https://api.github.com/users/Rameshb-umd/orgs',
        'repos_url': 'https://api.github.com/users/Rameshb-umd/repos',
        'events_url': 'https://api.github.com/users/Rameshb-umd/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/Rameshb-umd/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 53.026432
      },
      {
        'login': 'srameshr',
        'id': 8149408,
        'node_id': 'MDQ6VXNlcjgxNDk0MDg=',
        'avatar_url': 'https://avatars1.githubusercontent.com/u/8149408?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/srameshr',
        'html_url': 'https://github.com/srameshr',
        'followers_url': 'https://api.github.com/users/srameshr/followers',
        'following_url': 'https://api.github.com/users/srameshr/following{/other_user}',
        'gists_url': 'https://api.github.com/users/srameshr/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/srameshr/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/srameshr/subscriptions',
        'organizations_url': 'https://api.github.com/users/srameshr/orgs',
        'repos_url': 'https://api.github.com/users/srameshr/repos',
        'events_url': 'https://api.github.com/users/srameshr/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/srameshr/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 52.984043
      },
      {
        'login': 'krishnr',
        'id': 5304757,
        'node_id': 'MDQ6VXNlcjUzMDQ3NTc=',
        'avatar_url': 'https://avatars1.githubusercontent.com/u/5304757?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/krishnr',
        'html_url': 'https://github.com/krishnr',
        'followers_url': 'https://api.github.com/users/krishnr/followers',
        'following_url': 'https://api.github.com/users/krishnr/following{/other_user}',
        'gists_url': 'https://api.github.com/users/krishnr/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/krishnr/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/krishnr/subscriptions',
        'organizations_url': 'https://api.github.com/users/krishnr/orgs',
        'repos_url': 'https://api.github.com/users/krishnr/repos',
        'events_url': 'https://api.github.com/users/krishnr/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/krishnr/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 51.79809
      },
      {
        'login': 'rareddy',
        'id': 1268481,
        'node_id': 'MDQ6VXNlcjEyNjg0ODE=',
        'avatar_url': 'https://avatars3.githubusercontent.com/u/1268481?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rareddy',
        'html_url': 'https://github.com/rareddy',
        'followers_url': 'https://api.github.com/users/rareddy/followers',
        'following_url': 'https://api.github.com/users/rareddy/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rareddy/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rareddy/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rareddy/subscriptions',
        'organizations_url': 'https://api.github.com/users/rareddy/orgs',
        'repos_url': 'https://api.github.com/users/rareddy/repos',
        'events_url': 'https://api.github.com/users/rareddy/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rareddy/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 50.847885
      },
      {
        'login': 'rameshakulapc',
        'id': 6008085,
        'node_id': 'MDQ6VXNlcjYwMDgwODU=',
        'avatar_url': 'https://avatars0.githubusercontent.com/u/6008085?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rameshakulapc',
        'html_url': 'https://github.com/rameshakulapc',
        'followers_url': 'https://api.github.com/users/rameshakulapc/followers',
        'following_url': 'https://api.github.com/users/rameshakulapc/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rameshakulapc/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rameshakulapc/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rameshakulapc/subscriptions',
        'organizations_url': 'https://api.github.com/users/rameshakulapc/orgs',
        'repos_url': 'https://api.github.com/users/rameshakulapc/repos',
        'events_url': 'https://api.github.com/users/rameshakulapc/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rameshakulapc/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 50.63563
      },
      {
        'login': 'adityaramesh',
        'id': 1999682,
        'node_id': 'MDQ6VXNlcjE5OTk2ODI=',
        'avatar_url': 'https://avatars2.githubusercontent.com/u/1999682?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/adityaramesh',
        'html_url': 'https://github.com/adityaramesh',
        'followers_url': 'https://api.github.com/users/adityaramesh/followers',
        'following_url': 'https://api.github.com/users/adityaramesh/following{/other_user}',
        'gists_url': 'https://api.github.com/users/adityaramesh/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/adityaramesh/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/adityaramesh/subscriptions',
        'organizations_url': 'https://api.github.com/users/adityaramesh/orgs',
        'repos_url': 'https://api.github.com/users/adityaramesh/repos',
        'events_url': 'https://api.github.com/users/adityaramesh/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/adityaramesh/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 49.312904
      },
      {
        'login': 'ramesh130',
        'id': 5126298,
        'node_id': 'MDQ6VXNlcjUxMjYyOTg=',
        'avatar_url': 'https://avatars2.githubusercontent.com/u/5126298?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/ramesh130',
        'html_url': 'https://github.com/ramesh130',
        'followers_url': 'https://api.github.com/users/ramesh130/followers',
        'following_url': 'https://api.github.com/users/ramesh130/following{/other_user}',
        'gists_url': 'https://api.github.com/users/ramesh130/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/ramesh130/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/ramesh130/subscriptions',
        'organizations_url': 'https://api.github.com/users/ramesh130/orgs',
        'repos_url': 'https://api.github.com/users/ramesh130/repos',
        'events_url': 'https://api.github.com/users/ramesh130/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/ramesh130/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 49.085762
      },
      {
        'login': 'VRamazing',
        'id': 9432421,
        'node_id': 'MDQ6VXNlcjk0MzI0MjE=',
        'avatar_url': 'https://avatars0.githubusercontent.com/u/9432421?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/VRamazing',
        'html_url': 'https://github.com/VRamazing',
        'followers_url': 'https://api.github.com/users/VRamazing/followers',
        'following_url': 'https://api.github.com/users/VRamazing/following{/other_user}',
        'gists_url': 'https://api.github.com/users/VRamazing/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/VRamazing/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/VRamazing/subscriptions',
        'organizations_url': 'https://api.github.com/users/VRamazing/orgs',
        'repos_url': 'https://api.github.com/users/VRamazing/repos',
        'events_url': 'https://api.github.com/users/VRamazing/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/VRamazing/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 49.04318
      },
      {
        'login': 'RameshRM',
        'id': 1039362,
        'node_id': 'MDQ6VXNlcjEwMzkzNjI=',
        'avatar_url': 'https://avatars1.githubusercontent.com/u/1039362?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/RameshRM',
        'html_url': 'https://github.com/RameshRM',
        'followers_url': 'https://api.github.com/users/RameshRM/followers',
        'following_url': 'https://api.github.com/users/RameshRM/following{/other_user}',
        'gists_url': 'https://api.github.com/users/RameshRM/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/RameshRM/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/RameshRM/subscriptions',
        'organizations_url': 'https://api.github.com/users/RameshRM/orgs',
        'repos_url': 'https://api.github.com/users/RameshRM/repos',
        'events_url': 'https://api.github.com/users/RameshRM/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/RameshRM/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 48.855476
      },
      {
        'login': 'rameshsheth37',
        'id': 9636234,
        'node_id': 'MDQ6VXNlcjk2MzYyMzQ=',
        'avatar_url': 'https://avatars0.githubusercontent.com/u/9636234?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rameshsheth37',
        'html_url': 'https://github.com/rameshsheth37',
        'followers_url': 'https://api.github.com/users/rameshsheth37/followers',
        'following_url': 'https://api.github.com/users/rameshsheth37/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rameshsheth37/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rameshsheth37/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rameshsheth37/subscriptions',
        'organizations_url': 'https://api.github.com/users/rameshsheth37/orgs',
        'repos_url': 'https://api.github.com/users/rameshsheth37/repos',
        'events_url': 'https://api.github.com/users/rameshsheth37/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rameshsheth37/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 48.82601
      },
      {
        'login': 'rameshpaudel',
        'id': 3816783,
        'node_id': 'MDQ6VXNlcjM4MTY3ODM=',
        'avatar_url': 'https://avatars1.githubusercontent.com/u/3816783?v=4',
        'gravatar_id': '',
        'url': 'https://api.github.com/users/rameshpaudel',
        'html_url': 'https://github.com/rameshpaudel',
        'followers_url': 'https://api.github.com/users/rameshpaudel/followers',
        'following_url': 'https://api.github.com/users/rameshpaudel/following{/other_user}',
        'gists_url': 'https://api.github.com/users/rameshpaudel/gists{/gist_id}',
        'starred_url': 'https://api.github.com/users/rameshpaudel/starred{/owner}{/repo}',
        'subscriptions_url': 'https://api.github.com/users/rameshpaudel/subscriptions',
        'organizations_url': 'https://api.github.com/users/rameshpaudel/orgs',
        'repos_url': 'https://api.github.com/users/rameshpaudel/repos',
        'events_url': 'https://api.github.com/users/rameshpaudel/events{/privacy}',
        'received_events_url': 'https://api.github.com/users/rameshpaudel/received_events',
        'type': 'User',
        'site_admin': false,
        'score': 48.59438
      }
    ]
  };
  selectedUser: string;
  userDetails: any = [];

  constructor( private service: RestService, private appService: AppService) { 
  }

  // array of all items to be paged
  private allItems: any[];

  // pager object
  pager: any = {};
 
  // paged items
  pagedItems: any[];

  ngOnInit() {
 //  this.searchUsers();
  }

  setPage(page: number) {
    console.log('page ', page)
    // get pager object from service
    this.pager = this.appService.getPager(this.searchResult.items.length, page);

    // get current page of items
    this.pagedItems = this.searchResult.items.slice(this.pager.startIndex, this.pager.endIndex + 1);
}

  searchUsers(text) {
    this.service.searchUsers(text)
    .subscribe( resp => {
      console.log('success response', resp);
      this.searchResult = resp;
      console.log('success response', this.searchResult.items);
      // initialize to page 1
      this.setPage(1);
    }, error => {
      console.log('error response', error);
    });
  }
  onKey(event) {
    console.log(event, '  ', this.searchText);
    this.searchUsers(this.searchText);
  }

  getUserDetails(userName) {
    console.log(userName);
    this.selectedUser = userName;
    this.service.userDetails(userName)
    .subscribe( resp => {
      console.log('user detaisl ', resp);
      this.userDetails = resp;
    }, error => {
      console.log('error getting user details ', error);
    });
  }

  hideUserDetails(){
    this.selectedUser = '';
  }

}
